version: '3.4'
services:

  # The Application PHP Service
  app:
    build:
      context: ./
      dockerfile: laravelminio.app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./settings/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - app-network
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: laravelminio.web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
      - 443:443
    external_links:
     - database:database
    networks:
      - app-network
  # The Database
  database:
    image: mysql:5.6
    container_name: database
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./settings/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  # The minio
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: TCI4823FJXBK0206GOXX
      MINIO_SECRET_KEY: xHC90qBeyZW04r+4bWf8gOn2pYGlFhfLzgcotBGn
    command: server /data
    networks:
      - app-network
 #Docker Networks
networks:
  app-network:
    driver: bridge   
volumes:
  dbdata:
