version: '3'
services:

  #PHP Service
  app:
    image: geoincaks/lminio.app
    container_name: geoincaks.app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  wserver:
    image: geoincaks/lminio.wserver
    container_name: geoincaks.wserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #MySQL Service
  db:
    image: geoincaks/lminio.db
    container_name: geoincaks.db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
# The phpmyadmin
  phpmyadmin:
    depends_on:
            - db
    image: phpmyadmin/phpmyadmin
    container_name: geoincaks.phpmyadmin
    restart: always
    ports:
            - 3389:80
    environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
    networks:
            - app-network
# The minio
  minio:
    image: geoincaks/lminio.minio
    container_name: geoincaks.minio
    ports:
      - "8080:9000"
    volumes:
      - storage:/data
    environment:
      MINIO_ACCESS_KEY: TCI4823FJXBK0206GOXX
      MINIO_SECRET_KEY: xHC90qBeyZW04r+4bWf8gOn2pYGlFhfLzgcotBGn
    command: server /data
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  storage:
    driver: local
