version: '3.4'
services:

  # The Application PHP Service
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
      - 443:443
    external_links:
     - database:database
     - phpmyadmin:phpmyadmin
  # The Database
  database:
    image: mysql:5.6
    container_name: database
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=dbserver
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret
    external_links:
     - database:database      
    volumes:
     - "./phpmyadmin/sessions:/sessions"
  # The minio
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: TCI4823FJXBK0206GOXX
      MINIO_SECRET_KEY: xHC90qBeyZW04r+4bWf8gOn2pYGlFhfLzgcotBGn
    command: server /data
volumes:
  dbdata:
